name: main
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples
    runs-on: ubuntu-latest
    env:
      PLATFORM_DEFAULT_URL: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
    strategy:
      matrix:
        arduino-boards-fqbn:
          - esp32:esp32:esp32:CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M
          - esp32:esp32:esp32s2:CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install deps
        run: |
          npm i -g pnpm
          pip3 install littlefs-python esptool

      - name: Checkout EspAsyncWebServer
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/EspAsyncWebServer
          ref: master
          path: CustomLibrary_EspAsyncWebServer

      - name: Checkout AsyncTCP
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/AsyncTCP
          ref: master
          path: CustomLibrary_AsyncTCP

      - name: Compile
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          platform-default-url: ${{ env.PLATFORM_DEFAULT_URL }}
          platform-url: ${{ matrix.platform-url }}
          sketch-names: ${{ matrix.sketch-names }}
          sketches-exclude: ${{ matrix.sketches-exclude }}
          build-properties: ${{ toJson(matrix.build-properties) }}
          debug-install: true

      - name: Build client img
        run: |
          scripts/build-client-img.sh
          scripts/merge-bin.sh
          tree
      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            ESP32_Server_900u/build/**/*.bin
      - name: Prepare release
        run: |
          scripts/make-release.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.merged.*
